name: Test slack
on:
  pull_request:
    branches: ['master']
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check branch
        run: |
          echo ${{ github.head_ref }}
      
      - name: create messages
        run: echo "1st message\n" > temp.txt
      - name: next messages
        run: |
          ls -l temp.txt
          echo "[debug] next message" | tee -a temp.txt

      - name: make messages
        id: make_messages
        run: |
          msg="メンションのテスト\n"
          msg+="notify to <@U04UULP3WM7>\n"
          # msg+="$(cat temp.txt)"
          # echo "slk_msg=${msg}" >> $GITHUB_OUTPUT
          msg_blk=${{ fromJSON("[{"type": "context", "elements": [{"type": "mrkdwn", "text": "${msg}"}]}]") }}
          echo "slk_msg=${msg_blk}" >> $GITHUB_OUTPUT

      - name: post slack
        env:
          # MSG: '[{"type": "context", "elements": [{"type": "mrkdwn", "text": "${{ steps.make_messages.outputs.slk_msg }}"}]}]'
          MSG: ${{ toJSON(${{ steps.make_messages.outputs.slk_msg }}) }}
        run: |
          curl -X POST 'https://slack.com/api/chat.postMessage' \
            -d "token=${{ secrets.SLACK_BOT_TOKEN }}" \
            -d "channel=${{ secrets.SLACK_CHANNEL }}" \
            -d "blocks=${MSG}" \
            -d "thread_ts=1679068326.203699" \
            -d "reply_broadcast=false"
