name: context dump
on:
  pull_request:
    branches: ['master']
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check context
        run: |
          echo "::group::dump context"
          echo '${{ toJSON(github) }}'
          echo "::endgroup::"
