name: Test slack
on:
  pull_request:
    branches: ['master']
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check branch
        run: |
          echo ${{ github.head_ref }}
      
      - name: make messages
        id: make_messages
        run: |
          msg="メンションのテスト\n"
          msg+="notify to <@U04UULP3WM7>"
          echo "slk_msg=${msg}" >> $GITHUB_ENV

      - name: post slack
        run: |
          curl -X POST 'https://slack.com/api/chat.postMessage' \
            -d "token=${{ secrets.SLACK_BOT_TOKEN }}" \
            -d "channel=${{ secrets.SLACK_CHANNEL }}" \
            -d "blocks='[{\"type\": \"section\", \"text\": {\"type\": \"plain_text\", \"text\": \"${{ env.slk_msg }}\"}}]' \
            -d "thread_ts=1679068326.203699" \
            -d "reply_broadcast=false"
