name: Test slack
on:
  pull_request:
    branches: ['master']
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check branch
        run: |
          echo ${{ github.head_ref }}
      
      - name: make messages
        id: make_messages
        run: |
          msg="メンションのテスト\n"
          msg+="notify to <@U04UULP3WM7>"
          echo "slk_msg={\"type\": \"mrkdwn\", \"text\": \"${msg}\"}" >> $GITHUB_OUTPUT

      - name: post slack
        env:
          MSG: ${{ steps.make_messages.outputs.slk_msg }}
        run: |
          curl -X POST 'https://slack.com/api/chat.postMessage' \
            -d "token=${{ secrets.SLACK_BOT_TOKEN }}" \
            -d "channel=${{ secrets.SLACK_CHANNEL }}" \
            -d "blocks=${{ fromJSON('{"type": "context", "elements": ["${MSG}"]}') }}" \
            -d "thread_ts=1679068326.203699" \
            -d "reply_broadcast=false"
