name: Test slack
on:
  pull_request:
    branches: ['master']
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: make response messages
        id: make_response_messages
        run: |
          action_log="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          msg="Aggregation process *started*."
          msg+=" (<${action_log}|GitHub action log>)"
          echo "slk_msg=${msg}" >> $GITHUB_OUTPUT
          echo "action_log=${action_log}" >> $GITHUB_OUTPUT

      - name: response to slack
        env:
          MSG: ${{ steps.make_response_messages.outputs.slk_msg }}
        run: |
          curl -X POST 'https://slack.com/api/chat.postMessage' \
            -d "token=${{ secrets.SLACK_BOT_TOKEN }}" \
            -d "channel=${{ secrets.SLACK_CHANNEL }}" \
            -d "text=${MSG}" \
            -d "thread_ts=1679069687.520759" \
            -d "reply_broadcast=false" \
            -d "unfurl_links=false"

      - name: judge step
        id: judge_step
        run: |
          sleep 5
          # echo "[error] Error in this step."
          # exit 1

      - name: make messages
        id: make_messages
        if: ${{ always() }}
        run: |
          msg="<@mention>\n"
          msg+="Aggregation process *completed*.\n"
          if [ ${{ steps.judge_step.outcome }} == 'success' ]; then
            comment_url="${{ github.server_url }}"
            msg+=":white_check_mark: Please check the <${comment_url}|PR comment>."
          else
            msg+=":x: Please check the <${{ steps.make_response_messages.outputs.action_log }}|action log>."
          fi
          msg_blk="[{\"type\": \"context\", \"elements\": [{\"type\": \"mrkdwn\", \"text\": \"${msg}\"}]}]"
          echo "slk_msg=${msg_blk}" >> $GITHUB_OUTPUT

      - name: post slack
        if: ${{ always() }}
        env:
          MSG: ${{ steps.make_messages.outputs.slk_msg }}
        run: |
          curl -X POST 'https://slack.com/api/chat.postMessage' \
            -d "token=${{ secrets.SLACK_BOT_TOKEN }}" \
            -d "channel=${{ secrets.SLACK_CHANNEL }}" \
            -d "blocks=${MSG}" \
            -d "thread_ts=1679069687.520759" \
            -d "reply_broadcast=false"
