name: Test slack
on:
  pull_request:
    branches: ['master']
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check branch
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: judge step
        run: |
          exit 1

      - name: make messages
        id: make_messages
        if: ${{ always() }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          msg=""
          msg_blk="[{\"type\": \"context\", \"elements\": [{\"type\": \"mrkdwn\", \"text\": \"${msg}\"}]}]"
          echo "slk_msg=${msg_blk}" >> $GITHUB_OUTPUT

      # - name: post slack
      #   if: ${{ always() }}
      #   env:
      #     MSG: ${{ steps.make_messages.outputs.slk_msg }}
      #   run: |
      #     curl -X POST 'https://slack.com/api/chat.postMessage' \
      #       -d "token=${{ secrets.SLACK_BOT_TOKEN }}" \
      #       -d "channel=${{ secrets.SLACK_CHANNEL }}" \
      #       -d "blocks=${MSG}" \
      #       -d "thread_ts=1679069687.520759" \
      #       -d "reply_broadcast=false"
